name: "Lint and pubish"

on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Build Source
        run: yarn build
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "./bin/"
          author_name: Updater
          author_email: ahqsecret@gmail.com
          push: true
          message: "Push Packages"
