name: "Lint and pubish"

on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.3
        with:
          cache: "yarn"
      - name: Install Dependencies
        run: yarn Install
      - name: Build Source
        run: yarn Build
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Bla Bla Bla
        run: console.log("Hi!");
