name: "Build outputs and lint"

on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Build Source
        run: yarn build
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "./bin/"
          author_name: Updater
          author_email: ahqsecret@gmail.com
          push: true
          message: "Push Packages"
  lint:
    needs: [build]
    strategy:
      matrix:
        runner: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]
        packager: ['npm', 'yarn']

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Setup Linter Node ${{ matrix.node-version }} with ${{ matrix.packager }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.packager }}
      - name: Install
        run: ${{ matrix.packager }} install
      - name: Build with yarn
        if: matrix.packager == 'yarn'
        run: yarn add https://github.com/ahqsoftwares/slpl
      - name: Build with npm
        if: matrix.packager == 'npm'
        run: npm i . -g
      - name: Lint
        if: matrix.packager == 'npm'
        run: slpl
      - name: Lint with yarn
        if: matrix.packager == 'yarn'
        run: yarn slpl
